const normalizeLanguage = {
    "id": "id",
    "da": "da",
    "de": "de",
    "en-GB": "en",
    "en-US": "en",
    "es-ES": "es",
    "es-419": "es",
    "fr": "fr",
    "hr": "hr",
    "it": "it",
    "lt": "lt",
    "hu": "hu",
    "nl": "nl",
    "no": "no",
    "pl": "pl",
    "pt-BR": "pt",
    "ro": "ro",
    "fi": "fi",
    "sv-SE": "sv",
    "vi": "vi",
    "tr": "tr",
    "cs": "cs",
    "el": "el",
    "bg": "bg",
    "ru": "ru",
    "uk": "uk",
    "hi": "hi",
    "th": "th",
    "zh-CN": "zh",
    "ja": "ja",
    "zh-TW": "zh",
    "ko": "ko"
};

module.exports = normalizeLanguage;
